# Generated by Django 3.2.7 on 2021-09-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volonter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_rodjenja', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacija',
            fields=[
                ('pib', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('naziv', models.CharField(max_length=200, null=True)),
                ('opis', models.TextField(max_length=2000, null=True)),
                ('delatnost', models.CharField(max_length=100)),
                ('sajt', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=30)),
                ('sediste', models.CharField(max_length=200, null=True)),
                ('ulica', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
