# Generated by Django 3.2.7 on 2021-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volonter',
            name='pol',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='volonter',
            name='slika',
            field=models.ImageField(default='images/default.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='volonter',
            name='telefon',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
