# Generated by Django 3.2.7 on 2021-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210915_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='volonter',
            name='cv',
            field=models.FileField(default=None, upload_to='cv/'),
        ),
    ]
