# Generated by Django 3.2.7 on 2021-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210918_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskusija',
            name='naziv',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
