# Generated by Django 3.2.6 on 2021-09-08 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0002_alter_oglas_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='datum_isteka_oglasa',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 18, 41, 30, 695294)),
        ),
    ]
