# Generated by Django 3.2.6 on 2021-09-18 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0003_oglas_datum_isteka_oglasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum_isteka_oglasa',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 17, 39, 41, 701735)),
        ),
        migrations.AlterField(
            model_name='oglas',
            name='vidljivost',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Korisnici'), ('2', 'Volonteri')], default=1),
        ),
    ]
