# Generated by Django 3.2.6 on 2021-09-19 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0004_auto_20210918_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum_isteka_oglasa',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 9, 7, 51, 46899)),
        ),
        migrations.AlterField(
            model_name='oglas',
            name='vidljivost',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Korisnici'), (2, 'Volonteri')], default=1),
        ),
    ]
