# Generated by Django 3.2.6 on 2021-09-19 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0005_auto_20210919_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum_isteka_oglasa',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 9, 20, 22, 306531)),
        ),
    ]
